let table = document.getElementById('table')
let creattr = document.createElement('tr')
let creattdone = document.createElement('td')
creattdone.innerHTML = '';
let creattdtwo = document.createElement('td')
creattdtwo.innerHTML = '';
let creattdthree = document.createElement('td')
creattdthree.innerHTML = '';
let creattdfour = document.createElement('td')
creattdfour.innerHTML = '';
let creattdfive = document.createElement('td')
creattdfive.innerHTML = '';
let creattdsix = document.createElement('td')
creattdsix.innerHTML = '';
